<style type="text/css">
	   *{
			padding: 1px;
			font-family: cursive;
		}
		.header{
			border: 1px solid grey;
			height: 100px;
			background-color: #F0F0F0;
		}
		.link{
			display: block;
			background-color: lightgrey;
			width: 100px;
			float: left;
			padding: 20px 20px;
			margin-right: 30px;
			margin-left: 30px;
			margin-top: 3px;
			text-decoration: none;
			text-align: center;
			color: black;
		}
</style>
	<div class="header">
			<a class="link" href="./../category/grid.php">CATEGORY</a>
			<a class="link" href="./../customer/grid.php">CUSTOMER</a>
			<a class="link" href="./../vendor/grid.php">VENDOR</a>
			<a class="link" href="./../salesmen/grid.php">SALESMEN</a>
			<a class="link" href="./../product/grid.php">PRODUCT</a>
			<a class="link" href="./../shipping/grid.php">SHIPPING</a>
			<a class="link" href="./../payment/grid.php">PAYMENT</a>
	</div>
