<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<style>
		*{
			padding: 1px;
			font-family: cursive;
		}
		.footer{
			border: solid;
			height: 100px;
			background-color: #F0F0F0;
		}
	</style>
</head>
<div class="footer" align="center"> <h1> E-Commerce Website </h1> </div>
	</body>
</html>