<?php

$messageModel = new Model_Core_Message();
$messages = $messageModel->getMessage();

if ($messages) 
{
	foreach ($messages  as $type => $message) 
	{
		echo "<p class='{$type}'>";
		echo "$message";
		echo "</p>";
	}
}
$messageModel->clearMessage();
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<style>
		*{
			padding: 1px;
			font-family: cursive;
		}
		.header{
			border: solid;
			height: 100px;
			background-color: #F0F0F0;
		}
		.link{
			display: block;
			border-style: solid;
			background-color: lightgrey;
			width: 100px;
			float: left;
			padding: 20px 20px;
			margin-right: 30px;
			margin-left: 30px;
			margin-top: 10px;
			text-decoration: none;
			text-align: center;
			color: black;
		}
		.success{
			background-color: lightgreen;
			display: block;
			padding: 5px;
			margin: 5px;
		}
		.failure{
			background-color: lightred;
			display: block;
			padding: 5px;
			margin: 5px;
		}
		.notice{
			background-color: lightorange;
			display: block;
			padding: 5px;
			margin: 5px;
		}
	</style>
</head>
<div class="header">
	<table border="2">
		<tr align="center">
			<a class="link" href="index.php?c=category&a=grid">CATEGORY</a>
			<a class="link" href="index.php?c=customer&a=grid">CUSTOMER</a>
			<a class="link" href="index.php?c=payment&a=grid">PAYMENT</a>
			<a class="link" href="index.php?c=product&a=grid">PRODUCT</a>
			<a class="link" href="index.php?c=salesman&a=grid">SALESMEN</a>
			<a class="link" href="index.php?c=shipping&a=grid">SHIPPING</a>
			<a class="link" href="index.php?c=vendor&a=grid">VENDOR</a>
		</tr>
	</table>
	</div>
	</body>
</html>